### ISSUE TITLE
Add Celsius as a display option

### ISSUE THREAD

**Issue by Dontorpedo** [austinkregel/nova-weather-cards#2]
Hi is it possible to show Celscius instead of fahrenheit? didnt find any option to do this..

thanks in advance
D

**Comment by austinkregel** [comment]
According to [DarkSky's API Doc](https://darksky.net/dev/docs#forecast-request) it does look like this is an option, I can also add an option for a different language 🤔 

I'll create another ticket for translating the response into other languages!
